#!/bin/bash

# exit when any command fails
set -e
trap "exit \$?" INT TERM EXIT

source hooks/tags

for tag in "${TAGS[@]}"; do
    docker build .\
        --build-arg ubuntu_tag=${tag}\
        --cache-from ${DOCKER_REPO}:${tag}\
        -t ${DOCKER_REPO}:${tag}
done
