#!/bin/bash

source hooks/tags

for tag in "${TAGS[@]}"; do
    docker pull ${DOCKER_REPO}:${tag}
    docker build .\
        --build-arg ubuntu_tag=${tag}\
        --cache-from ${DOCKER_REPO}:${tag}\
        -t ${DOCKER_REPO}:${tag}
done
