#!/bin/bash

source hooks/tags

for tag in "${TAGS[@]}"; do
    # Start a container
    docker run\
        -dit\
        -v $(pwd):/workspace \
        --name ${tag}\
        ${DOCKER_REPO}:${tag}
    # Build the test project
    docker exec -i\
        --workdir "/workspace/test/executable"\
        ${tag}\
        bash "./build.sh"
    # Clean
    docker exec -i\
        --workdir "/workspace/test/executable"\
        ${tag}\
        bash "./build.sh"
    docker container stop ${tag}
    docker container rm ${tag}
done
